### ISSUE TITLE
Add `pkl_command` argument to `pkl.load`

### ISSUE THREAD

**Issue by miguelandres** [jw-y/pkl-python#4]
With a `pkl_command`, the PklServer could theoretically be started without downloading anything manually, many of us already have a suitable pkl command in our machines anyway, and downloading it is surprising behavior for a library.

**Comment by jw-y** [comment]
You are right. Thanks for the suggestion.

I was in the process of refining this behavior, but didn't have the time to finish this.

**Comment by jw-y** [comment]
This will be fixed from [c50b72e](https://github.com/jw-y/pkl-python/commit/c50b72ec1964a1aea63463ff3fff8fc38168326d)
