### ISSUE TITLE
Downloading the wrong architecture of the pkl binary on Apple Silicon Macs.

### ISSUE THREAD

**Issue by miguelandres** [jw-y/pkl-python#5]
The `detect_system` uses `platform.architecture()` to determine whether it's running on arm64 or amd64 and download the correct binary. 

However, `platform.architecture()` returns `64bit` on macOS for both Intel and Apple Silicon processors, therefore by default ARM macs get really slow performance due to emulation of AMD64 on arm64.

I think you meant to use `platform.machine()` in `detect_system`, I don't have other machines to test around me but I think that `platform.machine()` returns `aarch64` and `x86_64` pretty consistently on linux and it returns `arm64` and `x86_64` on macs (Notice it's `arm64` and not `aarch64`).

**Comment by jw-y** [comment]
Thanks for the report!

**Comment by jw-y** [comment]
This will be fixed from [c50b72e](https://github.com/jw-y/pkl-python/commit/c50b72ec1964a1aea63463ff3fff8fc38168326d)

**Comment by miguelandres** [comment]
Any chance you could cut a release with these fixes in ? Thanks!

**Comment by jw-y** [comment]
i will try to release it in a week or so

**Comment by jw-y** [comment]
> Any chance you could cut a release with these fixes in ? Thanks!

It is release here
https://github.com/jw-y/pkl-python/releases/tag/v0.1.15
